baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shree Kamatcheeammen Temple'
theme = ["github.com/bersennaidoo/bootstrap5theme"]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
