baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shree Kamatcheeammen Temple'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20
