baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shree Kamatcheeammen Temple'
theme = "bootstraptheme"

[[menus.main]]
name = 'HOME'
url = '/'
weight = 10

[[menus.main]]
name = "FIND US"
url = "/find-us"
weight = 20

[[menus.main]]
name = "RELIGIOUS SERVICES"
url = "/religious-services"
weight = 30

[[menus.main]]
name = "GALLERIES"
url = "/galleries"
weight = 40

[[menus.main]]
name = "PHOTO GALLERY"
url = "/galleries/photo-gallery"
parent = "/galleries"
weight = 45

[[menus.main]]
name = "SUPPORT US"
url = "/support-us"
weight = 50

[[menus.main]]
name = "ABOUT US"
url = "/about-us"
weight = 60
